import {
  CalendarDays,
  CaseUpper,
  Check,
  Highlighter,
  Image,
  Minus,
  MousePointer2,
  MessageSquarePlus,
  MoveUpRight,
  Pencil,
  PenLine,
  ScanLine,
  ScanText,
  Square,
  Stamp,
  TextCursorInput,
  Type,
  X,
} from "lucide-react";

export const tools = [
  {
    id: "comment",
    label: "Comment",
    icon: MessageSquarePlus,
    group: "annotate",
    hint: "Click the page to add a comment.",
  },
  {
    id: "select",
    label: "Select",
    icon: MousePointer2,
    group: "select",
    hint: "Select or move added objects. Shift-click to select several.",
  },
  { id: "text", label: "Text", icon: Type, group: "fill", hint: "Click the page to add text." },
  {
    id: "check",
    label: "Check",
    icon: Check,
    group: "fill",
    hint: "Click the page to place a checkmark.",
  },
  { id: "cross", label: "Cross", icon: X, group: "fill", hint: "Click the page to place a cross." },
  {
    id: "date",
    label: "Date",
    icon: CalendarDays,
    group: "fill",
    hint: "Click the page to add today's date.",
  },
  {
    id: "signature",
    label: "Sign",
    icon: PenLine,
    group: "sign",
    hint: "Add a visible signature. Certificate signing is available in Export.",
  },
  {
    id: "initials",
    label: "Initials",
    icon: CaseUpper,
    group: "sign",
    hint: "Draw, type or import your initials.",
  },
  {
    id: "image",
    label: "Image",
    icon: Image,
    group: "annotate",
    hint: "Choose an image, then click the page to place it.",
  },
  {
    id: "highlight",
    label: "Highlight",
    icon: Highlighter,
    group: "annotate",
    hint: "Drag across PDF text to highlight it, or drag elsewhere to highlight an area.",
  },
  {
    id: "ink",
    label: "Draw",
    icon: Pencil,
    group: "annotate",
    hint: "Drag to draw with a mouse, touch or pen.",
  },
  {
    id: "rectangle",
    label: "Box",
    icon: Square,
    group: "annotate",
    hint: "Drag to draw a rectangle. Covering content does not redact it.",
  },
  {
    id: "line",
    label: "Line",
    icon: Minus,
    group: "annotate",
    hint: "Drag from the start to the end of a line.",
  },
  {
    id: "arrow",
    label: "Arrow",
    icon: MoveUpRight,
    group: "annotate",
    hint: "Drag from the start to the end of an arrow.",
  },
  {
    id: "stamp",
    label: "Stamp",
    icon: Stamp,
    group: "annotate",
    hint: "Click to add a text stamp, then edit its wording.",
  },
  {
    id: "field",
    label: "Form field",
    icon: TextCursorInput,
    group: "field",
    hint: "Drag to create a fillable field, then choose its type in Properties.",
  },
] as const;

/** Whole-page scan processing, shown beside the placement tools so scans are easy to fix. */
export const scanTools = [
  {
    dialog: "ocr",
    label: "Recognize text",
    icon: ScanText,
    hint: "Make scanned pages searchable and selectable with on-device OCR.",
  },
  {
    dialog: "cleanup",
    label: "Clean up scans",
    icon: ScanLine,
    hint: "Detect and fix tilt, grey paper, faded text and dark edges.",
  },
] as const;
